// <auto-generated />
using System;
using ElasticSentinel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElasticSentinel.Migrations
{
    [DbContext(typeof(SentinelDbContext))]
    partial class SentinelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.AlertSchedulerConfig", b =>
                {
                    b.Property<short>("AlertSchedulerConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("alert_scheduler_config_id");

                    b.Property<string>("CronExp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_expression");

                    b.Property<short>("ElasticConfigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("elastic_configuration_id");

                    b.Property<short>("ElasticQueryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("elastic_query_id");

                    b.Property<short>("EmailAlertDetailId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_connector_detail_id");

                    b.Property<short>("EmailConnectorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_connector_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<short>("MSTeamsConnectorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teams_connector_id");

                    b.Property<short>("NotificationTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("notification_template_id");

                    b.Property<string>("SchedulerGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduler_group");

                    b.Property<string>("SchedulerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduler_name");

                    b.HasKey("AlertSchedulerConfigId");

                    b.HasIndex("ElasticConfigId");

                    b.HasIndex("ElasticQueryId");

                    b.HasIndex("EmailAlertDetailId");

                    b.HasIndex("EmailConnectorId");

                    b.HasIndex("MSTeamsConnectorId");

                    b.HasIndex("NotificationTemplateId");

                    b.ToTable("alert_scheduler_config");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.AlertSchedulerDetail", b =>
                {
                    b.Property<short>("AlertSchedulerDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("alert_scheduler_detail_id");

                    b.Property<short>("AlertSchedulerConfigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alert_scheduler_config_id");

                    b.Property<DateTime?>("LastRunDtTm")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_dttm");

                    b.Property<string>("LastRunStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_status");

                    b.Property<DateTime?>("QueryFilterDtTm")
                        .HasColumnType("TEXT")
                        .HasColumnName("query_filter_dttm");

                    b.HasKey("AlertSchedulerDetailId");

                    b.HasIndex("AlertSchedulerConfigId");

                    b.ToTable("alert_scheduler_detail");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.DocumentsProcessingDetail", b =>
                {
                    b.Property<int>("DocumentsProcessingDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("documents_processing_detail_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_dttm");

                    b.Property<string>("DocumentData")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_data");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_notified");

                    b.Property<int>("RetryAttempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_attempts");

                    b.Property<char>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("DocumentsProcessingDetailId");

                    b.ToTable("documents_processing_detail");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.ElasticConfiguration", b =>
                {
                    b.Property<short>("ElasticConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("elastic_configuration_id");

                    b.Property<string>("CertificateThumbprint")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("certificate_thumbprint");

                    b.Property<string>("ClusterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("cluster_name");

                    b.Property<string>("ElasticHost")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("ElasticConfigId");

                    b.ToTable("elastic_configuration");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.ElasticDynamicQueryRequestDetail", b =>
                {
                    b.Property<short>("ElasticDynamicQueryDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("elastic_dynamic_query_request_detail_id");

                    b.Property<string>("AuthType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_type");

                    b.Property<string>("Body")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message_body");

                    b.Property<string>("DyanmicQueryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_name");

                    b.Property<short>("ElasticDynamicQuerySourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("elastic_dynamic_query_source_id");

                    b.Property<string>("HTTPMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("http_method");

                    b.Property<string>("Headers")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("headers");

                    b.Property<string>("IndexName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("index_name");

                    b.Property<bool>("IsIndexNameExpression")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_index_expression");

                    b.Property<string>("QueryParams")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("query_params");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("query_type");

                    b.HasKey("ElasticDynamicQueryDetailId");

                    b.HasIndex("ElasticDynamicQuerySourceId");

                    b.ToTable("elastic_dynamic_query_request_detail");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.ElasticDynamicQueryResponseDetail", b =>
                {
                    b.Property<short>("ElasticDynamicQueryResponseDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("elastic_dynamic_query_response_detail_id");

                    b.Property<string>("QueryResponseMapperName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("query_response_mapper_name");

                    b.HasKey("ElasticDynamicQueryResponseDetailId");

                    b.ToTable("elastic_dynamic_query_response_detail");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.ElasticDynamicQueryResponseStructure", b =>
                {
                    b.Property<int>("ElasticDynamicQueryResponseStructureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("elastic_dynamic_query_response_structure_id");

                    b.Property<string>("AliasFieldName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("alias_field_name");

                    b.Property<short>("ElasticDynamicQueryResponseDetailId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("elastic_dynamic_query_response_detail_id");

                    b.Property<string>("IndexFieldName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("index_field_name");

                    b.Property<string>("IndexRootFieldName")
                        .HasColumnType("TEXT")
                        .HasColumnName("index_root_field_name");

                    b.Property<bool>("IsIndexFieldAnArray")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_index_field_array");

                    b.HasKey("ElasticDynamicQueryResponseStructureId");

                    b.HasIndex("ElasticDynamicQueryResponseDetailId");

                    b.ToTable("elastic_dynamic_query_response_structure");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.ElasticDynamicQuerySource", b =>
                {
                    b.Property<short>("ElasticDynamicQuerySourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("elastic_dynamic_query_source_id");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceQuery")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_query");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.HasKey("ElasticDynamicQuerySourceId");

                    b.ToTable("elastic_dynamic_query_source");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.ElasticQuery", b =>
                {
                    b.Property<short>("ElasticQueryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("elastic_query_id");

                    b.Property<short>("ElasticDynamicQueryDetailId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("elastic_dynamic_query_request_detail_id");

                    b.Property<short>("ElasticDynamicQueryResponseDetailId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("elastic_dynamic_query_response_detail_id");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_dynamic");

                    b.Property<string>("QueryDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("query_description");

                    b.Property<string>("QueryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("query_name");

                    b.HasKey("ElasticQueryId");

                    b.HasIndex("ElasticDynamicQueryDetailId");

                    b.HasIndex("ElasticDynamicQueryResponseDetailId");

                    b.ToTable("elastic_query");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.EmailConnector", b =>
                {
                    b.Property<short>("EmailConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_connector_id");

                    b.Property<string>("AlternateSMTPServer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("alternate_smtp_server");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_email");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_connector_name");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("PrimarySMTPServer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("smtp_server");

                    b.Property<int>("SMTPPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("smtp_port");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("EmailConnectorId");

                    b.ToTable("email_connector");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.EmailConnectorDetail", b =>
                {
                    b.Property<short>("EmailAlertDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_connector_detail_id");

                    b.Property<string>("CcEmails")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("cc_emails");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_subject");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_connector_detail_name");

                    b.Property<string>("ToEmails")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("to_emails");

                    b.HasKey("EmailAlertDetailId");

                    b.ToTable("email_connector_detail");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.MSTeamsConnector", b =>
                {
                    b.Property<short>("MSTeamsConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("teams_connector_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("teams_connector_name");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("webhook_url");

                    b.HasKey("MSTeamsConnectorId");

                    b.ToTable("teams_connector");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<short>("NotificationTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("notification_template_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("TemplateContent")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("template_content");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("template_name");

                    b.HasKey("NotificationTemplateId");

                    b.ToTable("notification_template");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.AlertSchedulerConfig", b =>
                {
                    b.HasOne("ElasticSentinel.Domain.Entities.ElasticConfiguration", "ElasticConfig")
                        .WithMany()
                        .HasForeignKey("ElasticConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElasticSentinel.Domain.Entities.ElasticQuery", "Query")
                        .WithMany("AlertSchedulerConfigs")
                        .HasForeignKey("ElasticQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElasticSentinel.Domain.Entities.EmailConnectorDetail", "MailConnectorDetail")
                        .WithMany("AlertSchedulerConfigs")
                        .HasForeignKey("EmailAlertDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElasticSentinel.Domain.Entities.EmailConnector", "MailConnector")
                        .WithMany("AlertSchedulerConfigs")
                        .HasForeignKey("EmailConnectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElasticSentinel.Domain.Entities.MSTeamsConnector", "TeamsConnector")
                        .WithMany("AlertSchedulerConfigs")
                        .HasForeignKey("MSTeamsConnectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElasticSentinel.Domain.Entities.NotificationTemplate", "Template")
                        .WithMany("AlertSchedulerConfigs")
                        .HasForeignKey("NotificationTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElasticConfig");

                    b.Navigation("MailConnector");

                    b.Navigation("MailConnectorDetail");

                    b.Navigation("Query");

                    b.Navigation("TeamsConnector");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.AlertSchedulerDetail", b =>
                {
                    b.HasOne("ElasticSentinel.Domain.Entities.AlertSchedulerConfig", "SchedulerConfig")
                        .WithMany("AlertSchedulerDetails")
                        .HasForeignKey("AlertSchedulerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchedulerConfig");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.ElasticDynamicQueryRequestDetail", b =>
                {
                    b.HasOne("ElasticSentinel.Domain.Entities.ElasticDynamicQuerySource", "QuerySource")
                        .WithMany("RequestDetails")
                        .HasForeignKey("ElasticDynamicQuerySourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuerySource");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.ElasticDynamicQueryResponseStructure", b =>
                {
                    b.HasOne("ElasticSentinel.Domain.Entities.ElasticDynamicQueryResponseDetail", "DynamicQueryResponseDetail")
                        .WithMany("QueryResponseStructures")
                        .HasForeignKey("ElasticDynamicQueryResponseDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicQueryResponseDetail");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.ElasticQuery", b =>
                {
                    b.HasOne("ElasticSentinel.Domain.Entities.ElasticDynamicQueryRequestDetail", "DynamicRequestDetail")
                        .WithMany()
                        .HasForeignKey("ElasticDynamicQueryDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElasticSentinel.Domain.Entities.ElasticDynamicQueryResponseDetail", "DynamicResponseDetail")
                        .WithMany("ElasticQueries")
                        .HasForeignKey("ElasticDynamicQueryResponseDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicRequestDetail");

                    b.Navigation("DynamicResponseDetail");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.AlertSchedulerConfig", b =>
                {
                    b.Navigation("AlertSchedulerDetails");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.ElasticDynamicQueryResponseDetail", b =>
                {
                    b.Navigation("ElasticQueries");

                    b.Navigation("QueryResponseStructures");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.ElasticDynamicQuerySource", b =>
                {
                    b.Navigation("RequestDetails");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.ElasticQuery", b =>
                {
                    b.Navigation("AlertSchedulerConfigs");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.EmailConnector", b =>
                {
                    b.Navigation("AlertSchedulerConfigs");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.EmailConnectorDetail", b =>
                {
                    b.Navigation("AlertSchedulerConfigs");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.MSTeamsConnector", b =>
                {
                    b.Navigation("AlertSchedulerConfigs");
                });

            modelBuilder.Entity("ElasticSentinel.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Navigation("AlertSchedulerConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
